In [1]:
import pandas as p

In [2]:
df=p.read_csv("HR.csv")

In [3]:
df

,Emp ID,Name Prefix,First Name,Middle Initial,Last Name,Gender,E Mail,Father's Name,Mother's Name,Mother's Maiden Name,...,SSN,Phone No.,Place Name,County,City,State,Zip,Region,User Name,Password
0,677509,Drs.,Lois,H,Walker,F,lois.walker@hotmail.com,Donald Walker,Helen Walker,Lewis,...,467-99-4677,303-572-8492,Denver,Denver,Denver,CO,80224,West,lhwalker,DCa}.T}X:v?NP
1,940761,Ms.,Brenda,S,Robinson,F,brenda.robinson@gmail.com,Raymond Robinson,Judy Robinson,Perry,...,537-71-4566,225-945-4954,Stonewall,De Soto,Stonewall,LA,71078,South,bsrobinson,TCo\j#Zg;SQ~o
2,428945,Dr.,Joe,W,Robinson,M,joe.robinson@gmail.com,Scott Robinson,Stephanie Robinson,Taylor,...,025-92-3584,219-904-2161,Michigantown,Clinton,Michigantown,IN,46057,Midwest,jwrobinson,GO4$J8MiEh[A
3,408351,Drs.,Diane,I,Evans,F,diane.evans@yahoo.com,Jason Evans,Michelle Evans,Allen,...,314-35-9851,215-793-6791,Hydetown,Crawford,Hydetown,PA,16328,Northeast,dievans,0gGRtp1HfL<r5
4,193819,Mr.,Benjamin,R,Russell,M,benjamin.russell@charter.net,Gregory Russell,Elizabeth Russell,Nelson,...,121-98-7248,262-404-2252,Fremont,Waupaca,Fremont,WI,54940,Midwest,brrussell,Rd<Y8cp!@R;*%F
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,639892,Mr.,Jose,K,Hill,M,jose.hill@hotmail.com,Carlos Hill,Anna Hill,Hayes,...,171-86-3825,228-245-5000,Biloxi,Harrison,Biloxi,MS,39532,South,jkhill,a_!SKb6h3?w*Mad
96,704709,Dr.,Harold,Z,Nelson,M,harold.nelson@gmail.com,Richard Nelson,Pamela Nelson,Smith,...,456-99-2066,217-555-9216,Carol Stream,Carol Stream,Carol Stream,IL,60351,Midwest,hznelson,z/-hEz3&^q5
97,461593,Ms.,Nicole,O,Ward,F,nicole.ward@yahoo.com,Ralph Ward,Julia Ward,Lee,...,196-84-2551,231-761-7861,Detroit,Wayne,Detroit,MI,48278,Midwest,noward,AUe6s0@:@]A3Ze
98,392491,Mrs.,Theresa,R,Murphy,F,theresa.murphy@gmail.com,George Murphy,Jacqueline Murphy,Peterson,...,249-99-8801,907-356-1555,Mc Grath,Yukon-Koyukuk (CA),Mc Grath,AK,99627,West,trmurphy,V]PGw>4h9
99,495141,Drs.,Tammy,B,Young,F,tammy.young@comcast.net,Andrew Young,Brenda Young,Robinson,...,771-02-7046,231-290-3075,Alma,Gratiot,Alma,MI,48801,Midwest,tbyoung,d6!&xu12A1H^i![

In [4]:
df.dtypes

Emp ID                      int64
Name Prefix                object
First Name                 object
Middle Initial             object
Last Name                  object
Gender                     object
E Mail                     object
Father's Name              object
Mother's Name              object
Mother's Maiden Name       object
Date of Birth              object
Time of Birth              object
Age in Yrs.               float64
Weight in Kgs.              int64
Date of Joining            object
Quarter of Joining         object
Half of Joining            object
Year of Joining             int64
Month of Joining            int64
Month Name of Joining      object
Short Month                object
Day of Joining              int64
DOW of Joining             object
Short DOW                  object
Age in Company (Years)    float64
Salary                      int64
Last % Hike                object
SSN                        object
Phone No.                  object
Place Name                 object
County                     object
City                       object
State                      object
Zip                         int64
Region                     object
User Name                  object
Password                   object
dtype: object

In [5]:
df.describe()

,Emp ID,Age in Yrs.,Weight in Kgs.,Year of Joining,Month of Joining,Day of Joining,Age in Company (Years),Salary,Zip
count,100.00000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
mean,547652.10000,39.238700,58.080000,2008.120000,6.250000,16.370000,8.978400,119738.090000,53011.230000
std,257664.16679,12.066252,12.294106,8.642484,3.453515,9.403046,8.657358,46185.278194,23007.336848
min,134841.00000,21.100000,40.000000,1983.000000,1.000000,1.000000,0.020000,42005.000000,3867.000000
25%,328643.75000,28.177500,50.000000,2003.000000,3.000000,7.000000,2.152500,83979.750000,37580.500000
50%,497414.00000,37.595000,56.000000,2010.500000,7.000000,18.000000,6.435000,118049.500000,52855.000000
75%,766040.00000,49.900000,61.250000,2015.000000,8.250000,24.000000,13.762500,162509.250000,69514.500000
max,979607.00000,59.470000,90.000000,2017.000000,12.000000,31.000000,34.520000,197537.000000,99791.000000

In [6]:
df.to_excel("HR1.xlsx",sheet_name="S1",index=False)

In [7]:
d=p.read_excel("HR1.xlsx")
d

,Emp ID,Name Prefix,First Name,Middle Initial,Last Name,Gender,E Mail,Father's Name,Mother's Name,Mother's Maiden Name,...,SSN,Phone No.,Place Name,County,City,State,Zip,Region,User Name,Password
0,677509,Drs.,Lois,H,Walker,F,lois.walker@hotmail.com,Donald Walker,Helen Walker,Lewis,...,467-99-4677,303-572-8492,Denver,Denver,Denver,CO,80224,West,lhwalker,DCa}.T}X:v?NP
1,940761,Ms.,Brenda,S,Robinson,F,brenda.robinson@gmail.com,Raymond Robinson,Judy Robinson,Perry,...,537-71-4566,225-945-4954,Stonewall,De Soto,Stonewall,LA,71078,South,bsrobinson,TCo\j#Zg;SQ~o
2,428945,Dr.,Joe,W,Robinson,M,joe.robinson@gmail.com,Scott Robinson,Stephanie Robinson,Taylor,...,025-92-3584,219-904-2161,Michigantown,Clinton,Michigantown,IN,46057,Midwest,jwrobinson,GO4$J8MiEh[A
3,408351,Drs.,Diane,I,Evans,F,diane.evans@yahoo.com,Jason Evans,Michelle Evans,Allen,...,314-35-9851,215-793-6791,Hydetown,Crawford,Hydetown,PA,16328,Northeast,dievans,0gGRtp1HfL<r5
4,193819,Mr.,Benjamin,R,Russell,M,benjamin.russell@charter.net,Gregory Russell,Elizabeth Russell,Nelson,...,121-98-7248,262-404-2252,Fremont,Waupaca,Fremont,WI,54940,Midwest,brrussell,Rd<Y8cp!@R;*%F
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,639892,Mr.,Jose,K,Hill,M,jose.hill@hotmail.com,Carlos Hill,Anna Hill,Hayes,...,171-86-3825,228-245-5000,Biloxi,Harrison,Biloxi,MS,39532,South,jkhill,a_!SKb6h3?w*Mad
96,704709,Dr.,Harold,Z,Nelson,M,harold.nelson@gmail.com,Richard Nelson,Pamela Nelson,Smith,...,456-99-2066,217-555-9216,Carol Stream,Carol Stream,Carol Stream,IL,60351,Midwest,hznelson,z/-hEz3&^q5
97,461593,Ms.,Nicole,O,Ward,F,nicole.ward@yahoo.com,Ralph Ward,Julia Ward,Lee,...,196-84-2551,231-761-7861,Detroit,Wayne,Detroit,MI,48278,Midwest,noward,AUe6s0@:@]A3Ze
98,392491,Mrs.,Theresa,R,Murphy,F,theresa.murphy@gmail.com,George Murphy,Jacqueline Murphy,Peterson,...,249-99-8801,907-356-1555,Mc Grath,Yukon-Koyukuk (CA),Mc Grath,AK,99627,West,trmurphy,V]PGw>4h9
99,495141,Drs.,Tammy,B,Young,F,tammy.young@comcast.net,Andrew Young,Brenda Young,Robinson,...,771-02-7046,231-290-3075,Alma,Gratiot,Alma,MI,48801,Midwest,tbyoung,d6!&xu12A1H^i![

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 37 columns):
Emp ID                    100 non-null int64
Name Prefix               100 non-null object
First Name                100 non-null object
Middle Initial            100 non-null object
Last Name                 100 non-null object
Gender                    100 non-null object
E Mail                    100 non-null object
Father's Name             100 non-null object
Mother's Name             100 non-null object
Mother's Maiden Name      100 non-null object
Date of Birth             100 non-null object
Time of Birth             100 non-null object
Age in Yrs.               100 non-null float64
Weight in Kgs.            100 non-null int64
Date of Joining           100 non-null object
Quarter of Joining        100 non-null object
Half of Joining           100 non-null object
Year of Joining           100 non-null int64
Month of Joining          100 non-null int64
Month Name of Joining     100 non-null object
Short Month               100 non-null object
Day of Joining            100 non-null int64
DOW of Joining            100 non-null object
Short DOW                 100 non-null object
Age in Company (Years)    100 non-null float64
Salary                    100 non-null int64
Last % Hike               100 non-null object
SSN                       100 non-null object
Phone No.                 100 non-null object
Place Name                100 non-null object
County                    100 non-null object
City                      100 non-null object
State                     100 non-null object
Zip                       100 non-null int64
Region                    100 non-null object
User Name                 100 non-null object
Password                  100 non-null object
dtypes: float64(2), int64(7), object(28)
memory usage: 29.0+ KB

In [9]:
df[["City","E Mail","Emp ID"]]

            City                        E Mail  Emp ID
0         Denver       lois.walker@hotmail.com  677509
1      Stonewall     brenda.robinson@gmail.com  940761
2   Michigantown        joe.robinson@gmail.com  428945
3       Hydetown         diane.evans@yahoo.com  408351
4        Fremont  benjamin.russell@charter.net  193819
..           ...                           ...     ...
95        Biloxi         jose.hill@hotmail.com  639892
96  Carol Stream       harold.nelson@gmail.com  704709
97       Detroit         nicole.ward@yahoo.com  461593
98      Mc Grath      theresa.murphy@gmail.com  392491
99          Alma       tammy.young@comcast.net  495141

[100 rows x 3 columns]

In [10]:
type(df)

pandas.core.frame.DataFrame

In [11]:
df.shape

(100, 37)

In [12]:
df[df["Day of Joining"]>20]

,Emp ID,Name Prefix,First Name,Middle Initial,Last Name,Gender,E Mail,Father's Name,Mother's Name,Mother's Maiden Name,...,SSN,Phone No.,Place Name,County,City,State,Zip,Region,User Name,Password
0,677509,Drs.,Lois,H,Walker,F,lois.walker@hotmail.com,Donald Walker,Helen Walker,Lewis,...,467-99-4677,303-572-8492,Denver,Denver,Denver,CO,80224,West,lhwalker,DCa}.T}X:v?NP
1,940761,Ms.,Brenda,S,Robinson,F,brenda.robinson@gmail.com,Raymond Robinson,Judy Robinson,Perry,...,537-71-4566,225-945-4954,Stonewall,De Soto,Stonewall,LA,71078,South,bsrobinson,TCo\j#Zg;SQ~o
4,193819,Mr.,Benjamin,R,Russell,M,benjamin.russell@charter.net,Gregory Russell,Elizabeth Russell,Nelson,...,121-98-7248,262-404-2252,Fremont,Waupaca,Fremont,WI,54940,Midwest,brrussell,Rd<Y8cp!@R;*%F
5,499687,Mr.,Patrick,F,Bailey,M,patrick.bailey@aol.com,Ralph Bailey,Laura Bailey,Henderson,...,439-99-7721,319-812-6957,Macksburg,Madison,Macksburg,IA,50155,Midwest,pfbailey,K7&5aY/*
7,380086,Mrs.,Carol,V,Murphy,F,carol.murphy@gmail.com,Eugene Murphy,Katherine Murphy,Peterson,...,423-67-7023,216-336-0009,Blanchester,Clinton,Blanchester,OH,45107,Midwest,cvmurphy,Uc+VG%vuZU<k
8,477616,Hon.,Frances,B,Young,F,frances.young@gmail.com,Fred Young,Lillian Young,Diaz,...,028-92-8912,210-819-9765,Delmita,Starr,Delmita,TX,78536,South,fbyoung,K}^USc0l7[A
12,386158,Mrs.,Melissa,Q,King,F,melissa.king@comcast.net,Philip King,Maria King,White,...,277-17-9106,216-605-3731,New Matamoras,Washington,New Matamoras,OH,45767,Midwest,mqking,FE5i<e-Y}[4f78
14,441771,Mrs.,Cheryl,O,Scott,F,cheryl.scott@gmail.com,Richard Scott,Lois Scott,Watson,...,596-94-2279,215-288-9345,Quecreek,Somerset,Quecreek,PA,15555,Northeast,coscott,Vbb+~2N|_yR
15,528509,Hon.,Paula,G,Diaz,F,paula.diaz@gmail.com,Alan Diaz,Kathryn Diaz,Powell,...,234-57-7671,252-531-7641,Beulaville,Duplin,Beulaville,NC,28518,South,pgdiaz,3Kg55luU
18,890290,Hon.,Julia,S,Scott,F,julia.scott@apple.com,Lawrence Scott,Amy Scott,King,...,251-99-1941,423-939-1010,Primm Springs,Hickman,Primm Springs,TN,38476,South,jsscott,r.:Q7c^Tpb
20,979607,Ms.,Carol,J,Edwards,F,carol.edwards@msn.com,Shawn Edwards,Susan Edwards,Gray,...,316-35-9870,225-283-4295,Shreveport,Caddo,Shreveport,LA,71162,South,cjedwards,wi>v-a9gt
22,426038,Hon.,Joan,C,Stewart,F,joan.stewart@yahoo.com,Charles Stewart,Julia Stewart,Collins,...,429-99-6443,216-637-6800,Middleport,Meigs,Middleport,OH,45760,Midwest,jcstewart,q@mq.U~D#1MPgZ
23,388642,Mrs.,Ruby,R,Rogers,F,ruby.rogers@gmail.com,Ronald Rogers,Teresa Rogers,Alexander,...,236-55-0172,423-231-6507,Woodbury,Cannon,Woodbury,TN,37190,South,rrrogers,t>#P@D9s<:9\V
25,477253,Mrs.,Anne,L,Russell,F,anne.russell@ibm.com,Jimmy Russell,Stephanie Russell,Richardson,...,456-99-5619,605-635-1306,Stockholm,Grant,Stockholm,SD,57264,Midwest,alrussell,c8Nk&Y^~Vz!2
27,683826,Mr.,Roger,L,Roberts,M,roger.roberts@gmail.com,Antonio Roberts,Katherine Roberts,Brooks,...,120-98-6493,206-497-3141,Mount Vernon,Skagit,Mount Vernon,WA,98273,West,rlroberts,41:C_0ik|Jb0iTO
32,621833,Mr.,Gregory,X,Edwards,M,gregory.edwards@outlook.com,Jose Edwards,Helen Edwards,Howard,...,010-94-6817,503-256-9654,Bonanza,Klamath,Bonanza,OR,97623,West,gxedwards,V^sVy*MO{
33,456747,Mr.,Roy,Z,Griffin,M,roy.griffin@yahoo.com,Benjamin Griffin,Wanda Griffin,Simmons,...,358-08-7660,219-506-9378,Liberty,Union,Liberty,IN,47353,Midwest,rzgriffin,qm&h<b.NsKaZ
35,333476,Hon.,Mary,P,Wilson,F,mary.wilson@sbcglobal.net,Robert Wilson,Jennifer Wilson,Patterson,...,198-84-0652,423-937-8660,Nashville,Davidson,Nashville,TN,37219,South,mpwilson,Pwl&W:|<_
42,265813,Hon.,Jack,E,Campbell,M,jack.campbell@gmail.com,Philip Campbell,Wanda Campbell,Watson,...,047-15-1537,316-499-5737,Kalvesta,Kalvesta,Kalvesta,KS,67856,Midwest,jecampbell,rh\N>WRr4hl~l
45,226714,Drs.,Nancy,L,Davis,F,nancy.davis@ibm.com,Bruce Davis,Jessica Davis,Moore,...,224-99-5928,219-610-3067,Bowling Green,Clay,Bowling Green,IN,47833,Midwest,nldavis,bv-KfTutT?0*pm
46,702813,Mr.,Ernest,D,Martinez,M,ernest.martinez@gmail.com,Ryan Martinez,Beverly Martinez,Hill,...,672-48-7749,479-951-4138,Uniontown,Crawford,Uniontown,AR,72955,South,edmartinez,qe?JNGBY{[\7;dD
47,524896,Ms.,Judy,Y,Hernandez,F,judy.hernandez@gmail.com,Fred Hernandez,Pamela Hernandez,Evans,...,534-71-4481,316-736-6126,Topeka,Shawnee,Topeka,KS,66606,Midwest,jyhernandez,kiB:v!j&?D!&NYY
50,958326,Mr.,Larry,T,Miller,M,larry.miller@shell.com,Russell Miller,Mildred Miller,Ward,...,207-84-9482,217-574-9283,East Saint Louis,St. Clair,East Saint Louis,IL,62201,Midwest,ltmiller,2WgF#:ew**x#
53,818384,Mr.,Peter,X,Washington,M,peter.washington@bp.com,Douglas Washington,Jean Washington,Henderson,...,039-74-8867,231-322-0316,Portage,Kalamazoo,Portage,MI,49024,Midwest,pxwashington,97%d^2rk41!E>*Q
54,971640,Prof.,Clarence,A,Ross,M,clarence.ross@apple.com,Arthur Ross,Louise Ross,Washington,...,372-37-5315,423-772-0118,Oneida,Scott,Oneida,TN,37841,South,caross,h&jmac@+QD?B
57,515103,Ms.,Anne,A,Perez,F,anne.perez@sbcglobal.net,Douglas Perez,Doris Perez,Bailey,...,594-99-9091,423-837-3338,Cookeville,Putnam,Cookeville,TN,38505,South,aaperez,y;n9A#}b
62,758872,Mr.,Henry,Y,Jenkins,M,henry.jenkins@hotmail.com,Albert Jenkins,Beverly Jenkins,Murphy,...,499-29-3125,314-731-7135,Riverside,Platte,Riverside,MO,64150,Midwest,hyjenkins,zPnRU5Bo
68,293459,Mr.,Steven,J,Phillips,M,steven.phillips@hotmail.com,Jason Phillips,Gloria Phillips,Lewis,...,578-53-9940,225-968-5952,Baton Rouge,East Baton Rouge,Baton Rouge,LA,70833,South,sjphillips,ht}X55$P&g1
70,915638,Dr.,Jason,W,Anderson,M,jason.anderson@gmail.com,Brandon Anderson,Julia Anderson,Baker,...,048-15-7937,217-856-6752,Hudson,McLean,Hudson,IL,61748,Midwest,jwanderson,a3Hlk+.V/TjD
72,951225,Ms.,Margaret,N,Brooks,F,margaret.brooks@gmail.com,Johnny Brooks,Debra Brooks,Robinson,...,057-02-6958,303-960-0117,Haswell,Kiowa,Haswell,CO,81045,West,mnbrooks,0*2k8uW&:{i{
74,528673,Hon.,Paul,V,Watson,M,paul.watson@hotmail.com,Carl Watson,Anna Watson,Bennett,...,286-15-9671,270-556-7711,Blue River,Floyd,Blue River,KY,41607,South,pvwatson,7q{iHhbgWZ7%
76,262382,Ms.,Cheryl,O,Miller,F,cheryl.miller@ntlworld.com,Gerald Miller,Christine Miller,Mitchell,...,287-15-4772,270-880-3858,Bays,Breathitt,Bays,KY,41310,South,comiller,Nr-t/.^cWBO
78,806955,Mr.,William,G,Hernandez,M,william.hernandez@rediffmail.com,Peter Hernandez,Deborah Hernandez,Jones,...,629-31-9010,239-276-0532,Mary Esther,Okaloosa,Mary Esther,FL,32569,South,wghernandez,BRB3DFywgZZ4
82,761821,Mr.,Ernest,G,Washington,M,ernest.washington@msn.com,Johnny Washington,Shirley Washington,Harris,...,178-86-1878,212-596-1659,Saranac Lake,Franklin,Saranac Lake,NY,12983,Northeast,egwashington,B\Wb^6W-
83,400173,Ms.,Dorothy,K,Edwards,F,dorothy.edwards@hotmail.co.uk,Dennis Edwards,Betty Edwards,Howard,...,543-81-2192,215-902-6888,Philadelphia,Philadelphia,Philadelphia,PA,19132,Northeast,dkedwards,VWEIm3YKm65|D
84,802554,Mr.,Ryan,V,Alexander,M,ryan.alexander@shell.com,William Alexander,Elizabeth Alexander,Gray,...,017-94-7572,225-395-3347,Jarreau,Pointe Coupee,Jarreau,LA,70749,South,rvalexander,3N3]VFZx?MaC{
92,969964,Hon.,Janice,S,Parker,F,janice.parker@yahoo.com,Paul Parker,Alice Parker,Perez,...,733-26-1976,314-842-5984,Whiteman Air Force Base,Johnson,Whiteman Air Force Base,MO,65305,Midwest,jsparker,8wUbWmuib
96,704709,Dr.,Harold,Z,Nelson,M,harold.nelson@gmail.com,Richard Nelson,Pamela Nelson,Smith,...,456-99-2066,217-555-9216,Carol Stream,Carol Stream,Carol Stream,IL,60351,Midwest,hznelson,z/-hEz3&^q5
97,461593,Ms.,Nicole,O,Ward,F,nicole.ward@yahoo.com,Ralph Ward,Julia Ward,Lee,...,196-84-2551,231-761-7861,Detroit,Wayne,Detroit,MI,48278,Midwest,noward,AUe6s0@:@]A3Ze
99,495141,Drs.,Tammy,B,Young,F,tammy.young@comcast.net,Andrew Young,Brenda Young,Robinson,...,771-02-7046,231-290-3075,Alma,Gratiot,Alma,MI,48801,Midwest,tbyoung,d6!&xu12A1H^i![

In [13]:
df[df["Day of Joining"].isin([21,22])]

,Emp ID,Name Prefix,First Name,Middle Initial,Last Name,Gender,E Mail,Father's Name,Mother's Name,Mother's Maiden Name,...,SSN,Phone No.,Place Name,County,City,State,Zip,Region,User Name,Password
5,499687,Mr.,Patrick,F,Bailey,M,patrick.bailey@aol.com,Ralph Bailey,Laura Bailey,Henderson,...,439-99-7721,319-812-6957,Macksburg,Madison,Macksburg,IA,50155,Midwest,pfbailey,K7&5aY/*
15,528509,Hon.,Paula,G,Diaz,F,paula.diaz@gmail.com,Alan Diaz,Kathryn Diaz,Powell,...,234-57-7671,252-531-7641,Beulaville,Duplin,Beulaville,NC,28518,South,pgdiaz,3Kg55luU
35,333476,Hon.,Mary,P,Wilson,F,mary.wilson@sbcglobal.net,Robert Wilson,Jennifer Wilson,Patterson,...,198-84-0652,423-937-8660,Nashville,Davidson,Nashville,TN,37219,South,mpwilson,Pwl&W:|<_
50,958326,Mr.,Larry,T,Miller,M,larry.miller@shell.com,Russell Miller,Mildred Miller,Ward,...,207-84-9482,217-574-9283,East Saint Louis,St. Clair,East Saint Louis,IL,62201,Midwest,ltmiller,2WgF#:ew**x#
62,758872,Mr.,Henry,Y,Jenkins,M,henry.jenkins@hotmail.com,Albert Jenkins,Beverly Jenkins,Murphy,...,499-29-3125,314-731-7135,Riverside,Platte,Riverside,MO,64150,Midwest,hyjenkins,zPnRU5Bo
70,915638,Dr.,Jason,W,Anderson,M,jason.anderson@gmail.com,Brandon Anderson,Julia Anderson,Baker,...,048-15-7937,217-856-6752,Hudson,McLean,Hudson,IL,61748,Midwest,jwanderson,a3Hlk+.V/TjD
78,806955,Mr.,William,G,Hernandez,M,william.hernandez@rediffmail.com,Peter Hernandez,Deborah Hernandez,Jones,...,629-31-9010,239-276-0532,Mary Esther,Okaloosa,Mary Esther,FL,32569,South,wghernandez,BRB3DFywgZZ4

In [14]:
df[df["Day of Joining"].isin([21,22])][["Day of Joining"]]

    Day of Joining
5               22
15              22
35              22
50              22
62              21
70              21
78              21

In [15]:
df["DOW of Joining"]

0        Monday
1        Sunday
2     Wednesday
3        Friday
4      Thursday
        ...
95     Saturday
96      Tuesday
97       Monday
98      Tuesday
99     Saturday
Name: DOW of Joining, Length: 100, dtype: object

In [16]:
df[(df["Day of Joining"].isin([20,21]))|(df["DOW of Joining"]=="Monday")]

,Emp ID,Name Prefix,First Name,Middle Initial,Last Name,Gender,E Mail,Father's Name,Mother's Name,Mother's Maiden Name,...,SSN,Phone No.,Place Name,County,City,State,Zip,Region,User Name,Password
0,677509,Drs.,Lois,H,Walker,F,lois.walker@hotmail.com,Donald Walker,Helen Walker,Lewis,...,467-99-4677,303-572-8492,Denver,Denver,Denver,CO,80224,West,lhwalker,DCa}.T}X:v?NP
9,162402,Hon.,Diana,T,Peterson,F,diana.peterson@hotmail.co.uk,Jonathan Peterson,Christina Peterson,Ross,...,512-33-6767,479-783-5656,Eureka Springs,Carroll,Eureka Springs,AR,72632,South,dtpeterson,3o8>v&tYxjyEAo
14,441771,Mrs.,Cheryl,O,Scott,F,cheryl.scott@gmail.com,Richard Scott,Lois Scott,Watson,...,596-94-2279,215-288-9345,Quecreek,Somerset,Quecreek,PA,15555,Northeast,coscott,Vbb+~2N|_yR
15,528509,Hon.,Paula,G,Diaz,F,paula.diaz@gmail.com,Alan Diaz,Kathryn Diaz,Powell,...,234-57-7671,252-531-7641,Beulaville,Duplin,Beulaville,NC,28518,South,pgdiaz,3Kg55luU
16,912990,Mr.,Joshua,T,Stewart,M,joshua.stewart@yahoo.ca,Todd Stewart,Martha Stewart,Jones,...,755-07-3676,217-279-9342,New Douglas,Madison,New Douglas,IL,62074,Midwest,jtstewart,K?vi9BBznj
17,214352,Ms.,Theresa,G,Lee,F,theresa.lee@gmail.com,John Lee,Rebecca Lee,Turner,...,055-02-9969,319-553-8919,Toeterville,Mitchell,Toeterville,IA,50481,Midwest,tglee,JS#hN&Xij\%QEr
20,979607,Ms.,Carol,J,Edwards,F,carol.edwards@msn.com,Shawn Edwards,Susan Edwards,Gray,...,316-35-9870,225-283-4295,Shreveport,Caddo,Shreveport,LA,71162,South,cjedwards,wi>v-a9gt
29,335732,Ms.,Brenda,M,Butler,F,brenda.butler@gmail.com,Phillip Butler,Joyce Butler,Thomas,...,282-15-6434,480-814-8284,Mesa,Maricopa,Mesa,AZ,85208,West,bmbutler,u+CtpZ~gyR*>
30,329752,Hon.,Lillian,X,Brown,F,lillian.brown@aol.com,Gary Brown,Virginia Brown,Wood,...,249-99-8821,239-812-9041,Panacea,Wakulla,Panacea,FL,32346,South,lxbrown,CG-M5~z:
40,923947,Ms.,Mary,G,Bryant,F,mary.bryant@verizon.net,Joshua Bryant,Norma Bryant,Harris,...,491-29-7461,319-827-3516,Conroy,Iowa,Conroy,IA,52220,Midwest,mgbryant,A[iR?Z1{
57,515103,Ms.,Anne,A,Perez,F,anne.perez@sbcglobal.net,Douglas Perez,Doris Perez,Bailey,...,594-99-9091,423-837-3338,Cookeville,Putnam,Cookeville,TN,38505,South,aaperez,y;n9A#}b
59,750173,Mr.,Antonio,R,Roberts,M,antonio.roberts@hotmail.com,Timothy Roberts,Diana Roberts,Rodriguez,...,281-15-7944,205-267-7304,Mc Calla,Jefferson,Mc Calla,AL,35111,South,arroberts,h>.g!B:VcNN
60,687017,Ms.,Frances,P,Watson,F,frances.watson@outlook.com,Adam Watson,Diana Watson,Jones,...,305-37-1946,406-530-8069,Trego,Lincoln,Trego,MT,59934,West,fpwatson,rjV1$at!wq53a$
62,758872,Mr.,Henry,Y,Jenkins,M,henry.jenkins@hotmail.com,Albert Jenkins,Beverly Jenkins,Murphy,...,499-29-3125,314-731-7135,Riverside,Platte,Riverside,MO,64150,Midwest,hyjenkins,zPnRU5Bo
70,915638,Dr.,Jason,W,Anderson,M,jason.anderson@gmail.com,Brandon Anderson,Julia Anderson,Baker,...,048-15-7937,217-856-6752,Hudson,McLean,Hudson,IL,61748,Midwest,jwanderson,a3Hlk+.V/TjD
74,528673,Hon.,Paul,V,Watson,M,paul.watson@hotmail.com,Carl Watson,Anna Watson,Bennett,...,286-15-9671,270-556-7711,Blue River,Floyd,Blue River,KY,41607,South,pvwatson,7q{iHhbgWZ7%
75,765850,Mrs.,Linda,R,Moore,F,linda.moore@gmail.com,Howard Moore,Diana Moore,Smith,...,286-15-5442,215-793-7095,Albion,Erie,Albion,PA,16401,Northeast,lrmoore,0jj}jl_r/VmJ;
76,262382,Ms.,Cheryl,O,Miller,F,cheryl.miller@ntlworld.com,Gerald Miller,Christine Miller,Mitchell,...,287-15-4772,270-880-3858,Bays,Breathitt,Bays,KY,41310,South,comiller,Nr-t/.^cWBO
78,806955,Mr.,William,G,Hernandez,M,william.hernandez@rediffmail.com,Peter Hernandez,Deborah Hernandez,Jones,...,629-31-9010,239-276-0532,Mary Esther,Okaloosa,Mary Esther,FL,32569,South,wghernandez,BRB3DFywgZZ4
81,225925,Mr.,Paul,D,Cooper,M,paul.cooper@gmail.com,Nicholas Cooper,Helen Cooper,Hill,...,613-87-0084,210-984-4722,Glidden,Colorado,Glidden,TX,78943,South,pdcooper,hW%ZbJ\fZ-
90,185032,Mr.,Eugene,D,Perez,M,eugene.perez@exxonmobil.com,Jimmy Perez,Lois Perez,Hall,...,192-86-6418,262-472-7112,Racine,Racine,Racine,WI,53490,Midwest,edperez,g]SJn<W_/#
91,867084,Ms.,Deborah,E,Smith,F,deborah.smith@yahoo.com,Richard Smith,Diana Smith,Bennett,...,173-86-6203,907-279-8694,Atqasuk,North Slope,Atqasuk,AK,99791,West,desmith,C[WxHsB9
97,461593,Ms.,Nicole,O,Ward,F,nicole.ward@yahoo.com,Ralph Ward,Julia Ward,Lee,...,196-84-2551,231-761-7861,Detroit,Wayne,Detroit,MI,48278,Midwest,noward,AUe6s0@:@]A3Ze

In [17]:
df.loc[(df["Day of Joining"].isin([21,22])),["Emp ID"]]

    Emp ID
5   499687
15  528509
35  333476
50  958326
62  758872
70  915638
78  806955

In [19]:
df.columns

Index(['Emp ID', 'Name Prefix', 'First Name', 'Middle Initial', 'Last Name',
       'Gender', 'E Mail', 'Father's Name', 'Mother's Name',
       'Mother's Maiden Name', 'Date of Birth', 'Time of Birth', 'Age in Yrs.',
       'Weight in Kgs.', 'Date of Joining', 'Quarter of Joining',
       'Half of Joining', 'Year of Joining', 'Month of Joining',
       'Month Name of Joining', 'Short Month', 'Day of Joining',
       'DOW of Joining', 'Short DOW', 'Age in Company (Years)', 'Salary',
       'Last % Hike', 'SSN', 'Phone No. ', 'Place Name', 'County', 'City',
       'State', 'Zip', 'Region', 'User Name', 'Password'],
      dtype='object')

In [20]:
df=df.rename(columns={"Emp ID":"ID"})

In [21]:
df["Age in Yrs."].mean()

39.23870000000001

In [22]:
df

,ID,Name Prefix,First Name,Middle Initial,Last Name,Gender,E Mail,Father's Name,Mother's Name,Mother's Maiden Name,...,SSN,Phone No.,Place Name,County,City,State,Zip,Region,User Name,Password
0,677509,Drs.,Lois,H,Walker,F,lois.walker@hotmail.com,Donald Walker,Helen Walker,Lewis,...,467-99-4677,303-572-8492,Denver,Denver,Denver,CO,80224,West,lhwalker,DCa}.T}X:v?NP
1,940761,Ms.,Brenda,S,Robinson,F,brenda.robinson@gmail.com,Raymond Robinson,Judy Robinson,Perry,...,537-71-4566,225-945-4954,Stonewall,De Soto,Stonewall,LA,71078,South,bsrobinson,TCo\j#Zg;SQ~o
2,428945,Dr.,Joe,W,Robinson,M,joe.robinson@gmail.com,Scott Robinson,Stephanie Robinson,Taylor,...,025-92-3584,219-904-2161,Michigantown,Clinton,Michigantown,IN,46057,Midwest,jwrobinson,GO4$J8MiEh[A
3,408351,Drs.,Diane,I,Evans,F,diane.evans@yahoo.com,Jason Evans,Michelle Evans,Allen,...,314-35-9851,215-793-6791,Hydetown,Crawford,Hydetown,PA,16328,Northeast,dievans,0gGRtp1HfL<r5
4,193819,Mr.,Benjamin,R,Russell,M,benjamin.russell@charter.net,Gregory Russell,Elizabeth Russell,Nelson,...,121-98-7248,262-404-2252,Fremont,Waupaca,Fremont,WI,54940,Midwest,brrussell,Rd<Y8cp!@R;*%F
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,639892,Mr.,Jose,K,Hill,M,jose.hill@hotmail.com,Carlos Hill,Anna Hill,Hayes,...,171-86-3825,228-245-5000,Biloxi,Harrison,Biloxi,MS,39532,South,jkhill,a_!SKb6h3?w*Mad
96,704709,Dr.,Harold,Z,Nelson,M,harold.nelson@gmail.com,Richard Nelson,Pamela Nelson,Smith,...,456-99-2066,217-555-9216,Carol Stream,Carol Stream,Carol Stream,IL,60351,Midwest,hznelson,z/-hEz3&^q5
97,461593,Ms.,Nicole,O,Ward,F,nicole.ward@yahoo.com,Ralph Ward,Julia Ward,Lee,...,196-84-2551,231-761-7861,Detroit,Wayne,Detroit,MI,48278,Midwest,noward,AUe6s0@:@]A3Ze
98,392491,Mrs.,Theresa,R,Murphy,F,theresa.murphy@gmail.com,George Murphy,Jacqueline Murphy,Peterson,...,249-99-8801,907-356-1555,Mc Grath,Yukon-Koyukuk (CA),Mc Grath,AK,99627,West,trmurphy,V]PGw>4h9
99,495141,Drs.,Tammy,B,Young,F,tammy.young@comcast.net,Andrew Young,Brenda Young,Robinson,...,771-02-7046,231-290-3075,Alma,Gratiot,Alma,MI,48801,Midwest,tbyoung,d6!&xu12A1H^i![

In [23]:
df[["ID","Age in Yrs."]]

        ID  Age in Yrs.
0   677509        36.36
1   940761        47.02
2   428945        54.15
3   408351        39.67
4   193819        40.31
..     ...          ...
95  639892        22.82
96  704709        32.61
97  461593        52.66
98  392491        29.60
99  495141        38.38

[100 rows x 2 columns]

In [24]:
df.agg({"Age in Yrs.":["min","max"],"Weight in Kgs.":["mean","median"]})

        Age in Yrs.  Weight in Kgs.
max           59.47             NaN
mean            NaN           58.08
median          NaN           56.00
min           21.10             NaN

In [25]:
df["Quarter of Joining"].unique()

array(['Q4', 'Q3', 'Q2', 'Q1'], dtype=object)

In [26]:
df["Quarter of Joining"].value_counts()

Q3    32
Q1    26
Q2    23
Q4    19
Name: Quarter of Joining, dtype: int64

In [27]:
df["Quarter of Joining"].unique()

array(['Q4', 'Q3', 'Q2', 'Q1'], dtype=object)

In [28]:
df.sort_values(by="Weight in Kgs.").head()

,ID,Name Prefix,First Name,Middle Initial,Last Name,Gender,E Mail,Father's Name,Mother's Name,Mother's Maiden Name,...,SSN,Phone No.,Place Name,County,City,State,Zip,Region,User Name,Password
41,227922,Hon.,Amanda,M,Hughes,F,amanda.hughes@rediffmail.com,Roy Hughes,Cynthia Hughes,Bryant,...,311-35-2540,225-544-9700,Lake Charles,Calcasieu,Lake Charles,LA,70605,South,amhughes,B2N>J{_k7]F
7,380086,Mrs.,Carol,V,Murphy,F,carol.murphy@gmail.com,Eugene Murphy,Katherine Murphy,Peterson,...,423-67-7023,216-336-0009,Blanchester,Clinton,Blanchester,OH,45107,Midwest,cvmurphy,Uc+VG%vuZU<k
75,765850,Mrs.,Linda,R,Moore,F,linda.moore@gmail.com,Howard Moore,Diana Moore,Smith,...,286-15-5442,215-793-7095,Albion,Erie,Albion,PA,16401,Northeast,lrmoore,0jj}jl_r/VmJ;
47,524896,Ms.,Judy,Y,Hernandez,F,judy.hernandez@gmail.com,Fred Hernandez,Pamela Hernandez,Evans,...,534-71-4481,316-736-6126,Topeka,Shawnee,Topeka,KS,66606,Midwest,jyhernandez,kiB:v!j&?D!&NYY
51,447813,Mrs.,Ann,Q,Coleman,F,ann.coleman@ibm.com,Harold Coleman,Tina Coleman,Walker,...,027-92-0557,319-994-4179,Hancock,Pottawattamie,Hancock,IA,51536,Midwest,aqcoleman,g2]GlvlL5